name: My-First-Git-Action-pipeline
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
        -   name: First Step
            run: echo "Hello Mytresh"
        -   name: Seocond Step
            run: echo "Bye Mytresh"
        -   name: Third Step
            run: |
                echo "Happy Good Morning"
                echo "Happy Good Afternoon"
                echo "Happy Good Night"
            